language: php

php:
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --dev --no-update squizlabs/php_codesniffer
  - travis_retry composer require codeclimate/php-test-reporter --dev
  - travis_retry composer require sensiolabs/security-checker --dev
  - travis_retry composer install --prefer-dist --no-interaction

notifications:
    email: false

script:
  - vendor/bin/phpcs --colors -p --standard=PSR2 --encoding=utf-8 -n src/
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
  - vendor/bin/test-reporter --coverage-report=coverage.xml
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
