name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test code base
    runs-on: ubuntu-latest
    steps:
      - name: Prepare PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mysql, apcu, mbstring, xml, json, soap, intl, curl, gd, gmp, gettext, zip
          ini-values: phar.readonly=0, pcov.directory=.
          coverage: pcov
          tools: php-cs-fixer, phpunit, codeception, composer
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install
        id: composer-install
        run: composer install

      - name: Run tests
        id: run-tests
        run: composer run tests
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send report to Code Climate
        id: code-climate-report
        run: vendor/bin/test-reporter --coverage-report=coverage.xml
        env:
          DEFAULT_BRANCH: master
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
